import { Platform, StatusBar, StyleSheet } from "react-native";

import { getAndroidStatusBarTopInset } from "../lib/safe-area";

export const palette = {
  ink: "#18181b",
  muted: "#71717a",
  paper: "#fafafa",
  wash: "#f4f4f5",
  line: "#d4d4d8",
  lineSoft: "#e4e4e7",
  lineSubtle: "rgba(24,24,27,0.08)",
  white: "#ffffff",
  green: "#0f766e",
  greenSoft: "#ecfdf5",
  greenBold: "#115e59",
  greenLine: "#99f6e4",
  amber: "#b45309",
  amberSoft: "#fffbeb",
  amberBold: "#92400e",
  amberLine: "#fde68a",
  red: "#b91c1c",
  redSoft: "#fef2f2",
  redLine: "#fecaca",
  surfaceElevated: "#ffffff",
  inverseText: "#ffffff",
  inverseMuted: "#e4e4e7",
  shadow: "rgba(24,24,27,0.08)",
  shadowMedium: "rgba(24,24,27,0.14)",
  shadowStrong: "rgba(24,24,27,0.25)",
  blueBill: "#1d4ed8",
  blueBillSoft: "#eff6ff",
  scanner: "#111827"
};

export const androidStatusBarTopInset = getAndroidStatusBarTopInset(Platform.OS, StatusBar.currentHeight);

export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: palette.wash, paddingTop: androidStatusBarTopInset },
  keyboardShell: { flex: 1 },
  loadingShell: { flex: 1, alignItems: "center", justifyContent: "center", gap: 12 },
  loadingText: { color: palette.ink, fontWeight: "800" },
  screen: { flex: 1 },
  screenContent: { paddingHorizontal: 16, paddingTop: 12, paddingBottom: 118, gap: 12 },
  virtualMenuContent: { flex: 1 },
  onboardingContent: { paddingHorizontal: 16, paddingTop: 12, paddingBottom: 34, gap: 12 },
  header: {
    paddingHorizontal: 16,
    paddingTop: 14,
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: palette.line,
    backgroundColor: palette.paper,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
    zIndex: 10,
    elevation: 0
  },
  headerText: { flex: 1, minWidth: 0 },
  headerActions: { alignItems: "flex-end", gap: 6 },
  flexText: { flex: 1, minWidth: 0 },
  kicker: { color: palette.greenBold, fontWeight: "800", fontSize: 13, textTransform: "uppercase", letterSpacing: 0.4 },
  title: { fontSize: 24, fontWeight: "900", color: palette.ink, lineHeight: 30 },
  heroTitle: { color: palette.ink, fontSize: 28, fontWeight: "900", lineHeight: 34 },
  heroCopy: { color: palette.muted, fontSize: 14, lineHeight: 21 },
  muted: { color: palette.muted, fontSize: 12, fontWeight: "700", lineHeight: 18 },
  smallMuted: { color: palette.muted, fontSize: 12, fontWeight: "700", lineHeight: 18, paddingVertical: 4 },
  heroPanel: {
    borderRadius: 8,
    backgroundColor: palette.paper,
    borderWidth: 1,
    borderColor: palette.line,
    padding: 18,
    gap: 7,
    elevation: 0
  },
  stepCard: {
    padding: 18,
    gap: 12,
    backgroundColor: palette.paper,
    borderWidth: 1,
    borderColor: palette.line,
    borderRadius: 8,
    elevation: 0
  },
  stepHeader: { flexDirection: "row", alignItems: "center", gap: 10 },
  stepCircle: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: palette.greenBold,
    alignItems: "center",
    justifyContent: "center"
  },
  stepCircleText: { color: palette.inverseText, fontWeight: "900", fontSize: 16 },
  banner: {
    borderWidth: 1,
    borderColor: palette.line,
    backgroundColor: palette.paper,
    borderRadius: 8,
    padding: 12,
    gap: 3
  },
  bannerWarning: { borderColor: palette.amberLine, backgroundColor: palette.amberSoft },
  bannerText: { color: palette.ink, fontWeight: "800", lineHeight: 20 },
  bannerMeta: { color: palette.green, fontSize: 12, fontWeight: "800" },
  dot: { width: 12, height: 12, borderRadius: 6 },
  online: { backgroundColor: palette.green },
  offline: { backgroundColor: palette.red },
  checking: { backgroundColor: palette.amber },
  statusPill: {
    minHeight: 34,
    borderRadius: 999,
    borderWidth: 1,
    paddingHorizontal: 10,
    paddingVertical: 4,
    flexDirection: "row",
    alignItems: "center",
    gap: 6
  },
  status_online: { borderColor: palette.greenLine, backgroundColor: palette.greenSoft },
  status_offline: { borderColor: palette.redLine, backgroundColor: palette.redSoft },
  status_checking: { borderColor: palette.amberLine, backgroundColor: palette.amberSoft },
  statusText: { color: palette.ink, fontWeight: "800", fontSize: 13 },
  iconButton: {
    minHeight: 40,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: palette.line,
    paddingHorizontal: 14,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: palette.paper
  },
  iconButtonText: { color: palette.ink, fontWeight: "800", fontSize: 13 },
  cardHeader: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 10 },
  sectionTitle: { fontSize: 18, fontWeight: "900", color: palette.ink },
  serviceStats: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  serviceStat: {
    minWidth: 86,
    flexGrow: 1,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: palette.line,
    backgroundColor: palette.white,
    padding: 10,
    gap: 4
  },
  serviceStatWide: {
    minWidth: 142,
    flexGrow: 2,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: palette.greenLine,
    backgroundColor: palette.greenSoft,
    padding: 10,
    gap: 4
  },
  serviceStatValue: { color: palette.ink, fontSize: 18, fontWeight: "900" },
  inputGroup: { gap: 6 },
  inputLabel: { color: palette.muted, fontSize: 13, fontWeight: "700", textTransform: "uppercase", letterSpacing: 0.2 },
  input: {
    minHeight: 44,
    borderWidth: 1,
    borderColor: palette.line,
    borderRadius: 8,
    paddingHorizontal: 12,
    color: palette.ink,
    backgroundColor: palette.white,
    fontWeight: "600"
  },
  multilineInput: {
    minHeight: 76,
    paddingTop: 11,
    paddingBottom: 11
  },
  buttonStack: { gap: 8 },
  primaryButton: {
    minHeight: 44,
    borderRadius: 8,
    backgroundColor: palette.ink,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 16
  },
  primaryButtonText: { color: palette.inverseText, fontWeight: "800" },
  secondaryButton: {
    minHeight: 44,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: palette.line,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 14,
    backgroundColor: palette.paper
  },
  secondaryButtonText: { color: palette.ink, fontWeight: "800" },
  approvalActionActive: { backgroundColor: palette.greenSoft, borderColor: palette.green },
  approvalDangerActive: { backgroundColor: palette.red },
  scanButton: {
    minHeight: 56,
    borderRadius: 8,
    backgroundColor: palette.green,
    alignItems: "center",
    justifyContent: "center",
    gap: 3
  },
  scanButtonText: { color: palette.inverseText, fontSize: 17, fontWeight: "800" },
  scanButtonMeta: { color: palette.greenLine, fontSize: 12, fontWeight: "700" },
  modeTabs: {
    flexDirection: "row",
    padding: 5,
    borderRadius: 8,
    backgroundColor: palette.wash,
    borderWidth: 1,
    borderColor: palette.line
  },
  modeTab: { flex: 1, minHeight: 42, alignItems: "center", justifyContent: "center", borderRadius: 6, position: "relative" as const },
  modeTabActive: { backgroundColor: palette.ink },
  modeTabText: { color: palette.ink, fontWeight: "800", fontSize: 13 },
  modeTabTextActive: { color: palette.inverseText },
  modeBadge: {
    position: "absolute" as const,
    top: -2,
    right: -2,
    minWidth: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: palette.green,
    alignItems: "center" as const,
    justifyContent: "center" as const,
    paddingHorizontal: 4
  },
  modeBadgeText: { color: palette.inverseText, fontSize: 11, fontWeight: "900" },
  workArea: { gap: 12 },
  workAreaMenuOnly: { flex: 1 },
  workAreaWide: { flexDirection: "row", alignItems: "flex-start" },
  panel: {
    borderWidth: 1,
    borderColor: palette.line,
    borderRadius: 8,
    backgroundColor: palette.paper,
    padding: 14,
    gap: 12
  },
  menuPanel: { flex: 1 },
  virtualMenuPanel: { padding: 0, overflow: "hidden" },
  floorTableStack: { gap: 12 },
  floorTableGroup: { gap: 8 },
  floorTableHeader: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 8 },
  tableGrid: { flexDirection: "row", flexWrap: "wrap", gap: 12 },
  tableTile: {
    minHeight: 92,
    padding: 12,
    borderWidth: 0,
    borderLeftWidth: 5,
    borderColor: palette.green,
    borderRadius: 8,
    backgroundColor: palette.surfaceElevated,
    justifyContent: "space-between",
    shadowColor: palette.shadow,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 6,
    shadowOpacity: 1,
    elevation: 3
  },
  busyTable: { borderColor: palette.amberBold, backgroundColor: palette.amberSoft },
  billedTable: { borderColor: palette.blueBill, backgroundColor: palette.blueBillSoft },
  selectedTable: { borderColor: palette.greenBold, backgroundColor: palette.greenSoft, shadowRadius: 10, elevation: 5 },
  tableName: { fontSize: 20, fontWeight: "900", color: palette.ink },
  tableStatus: { color: palette.green, fontWeight: "900", fontSize: 12 },
  tableStatusBusy: { color: palette.amberBold },
  tableStatusBilled: { color: palette.blueBill },
  kitchenPanel: { gap: 14 },
  kotList: { gap: 10 },
  kotCard: {
    borderWidth: 0,
    borderLeftWidth: 4,
    borderColor: palette.amber,
    borderRadius: 8,
    backgroundColor: palette.amberSoft,
    padding: 16,
    gap: 12,
    shadowColor: palette.shadow,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 8,
    shadowOpacity: 1,
    elevation: 3
  },
  kotCardPreparing: { borderColor: palette.green, backgroundColor: palette.greenSoft },
  kotCardReady: { borderColor: palette.greenBold, backgroundColor: palette.greenSoft },
  kotCardServed: { borderColor: palette.line, backgroundColor: palette.wash, opacity: 0.7 },
  kotHeader: { flexDirection: "row", alignItems: "flex-start", justifyContent: "space-between", gap: 10 },
  kotTable: { color: palette.ink, fontSize: 26, fontWeight: "900", lineHeight: 32 },
  kotStatusPill: {
    minHeight: 34,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: palette.line,
    backgroundColor: palette.paper,
    paddingHorizontal: 12,
    alignItems: "center",
    justifyContent: "center"
  },
  kotStatusReady: { borderColor: palette.greenBold, backgroundColor: palette.greenSoft },
  kotStatusText: { color: palette.muted, fontSize: 13, fontWeight: "900", textTransform: "uppercase" },
  kotStatusTextReady: { color: palette.greenBold },
  kotItems: { gap: 8 },
  kotItemRow: {
    minHeight: 48,
    borderRadius: 8,
    backgroundColor: palette.white,
    borderWidth: 1,
    borderColor: palette.lineSubtle,
    paddingHorizontal: 12,
    flexDirection: "row",
    alignItems: "center",
    gap: 10
  },
  kotQty: { minWidth: 36, color: palette.greenBold, fontSize: 20, fontWeight: "900" },
  kotItemName: { flex: 1, color: palette.ink, fontSize: 18, fontWeight: "800", lineHeight: 22 },
  kotActions: { flexDirection: "row", gap: 8 },
  kotActionButton: { flex: 1, minHeight: 54 },
  shiftGrid: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  shiftActionCard: {
    borderRadius: 8,
    borderWidth: 1,
    borderColor: palette.lineSoft,
    backgroundColor: palette.white,
    padding: 10,
    gap: 10
  },
  shiftButton: {
    minHeight: 48,
    minWidth: 76,
    paddingHorizontal: 14,
    borderRadius: 8,
    backgroundColor: palette.surfaceElevated,
    borderWidth: 1,
    borderColor: palette.line,
    alignItems: "center",
    justifyContent: "center"
  },
  shiftButtonActive: { backgroundColor: palette.greenSoft, borderColor: palette.green },
  shiftButtonText: { color: palette.ink, fontWeight: "800" },
  shiftButtonMeta: { color: palette.muted, fontWeight: "700", fontSize: 11 },
  fieldBlock: { gap: 8 },
  actionSection: {
    borderRadius: 8,
    borderWidth: 1,
    borderColor: palette.line,
    backgroundColor: palette.wash,
    padding: 12,
    gap: 10
  },
  sectionHeaderRow: { flexDirection: "row", alignItems: "flex-start", justifyContent: "space-between", gap: 10 },
  actionTitle: { color: palette.ink, fontSize: 17, fontWeight: "900", lineHeight: 22 },
  actionMeta: { color: palette.muted, fontSize: 12, fontWeight: "700", lineHeight: 17 },
  actionAmount: { color: palette.green, fontSize: 16, fontWeight: "900" },
  sendButtonRow: { flexDirection: "row", gap: 8 },
  heroSendButton: { minHeight: 62 },
  itemShiftRow: {
    minHeight: 52,
    borderWidth: 1,
    borderColor: palette.lineSoft,
    backgroundColor: palette.white,
    borderRadius: 8,
    padding: 8,
    flexDirection: "row",
    alignItems: "center",
    gap: 8
  },
  shiftQtyInput: {
    width: 42,
    minHeight: 38,
    borderWidth: 1,
    borderColor: palette.line,
    borderRadius: 8,
    textAlign: "center",
    color: palette.ink,
    fontWeight: "900",
    backgroundColor: palette.paper
  },
  transferQtyStepper: { flexDirection: "row", alignItems: "center", gap: 4, flexShrink: 0 },
  transferQtyButton: {
    width: 38,
    height: 38,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: palette.line,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: palette.wash
  },
  targetPickerList: { gap: 6 },
  targetPickerRow: {
    minHeight: 52,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: palette.lineSoft,
    backgroundColor: palette.white,
    paddingHorizontal: 12,
    paddingVertical: 8,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10
  },
  cancelPanel: {
    gap: 8,
    borderColor: palette.redLine,
    backgroundColor: palette.redSoft
  },
  stateEditor: {
    borderRadius: 8,
    borderWidth: 1,
    borderColor: palette.line,
    backgroundColor: palette.white,
    padding: 10,
    gap: 10
  },
  stateSearchResults: {
    gap: 8,
    maxHeight: 360
  },
  savedStatePill: {
    minHeight: 38,
    alignSelf: "flex-start",
    borderRadius: 8,
    borderWidth: 1,
    borderColor: palette.line,
    backgroundColor: palette.paper,
    paddingHorizontal: 12,
    alignItems: "center",
    justifyContent: "center"
  },
  savedStateText: { color: palette.muted, fontSize: 12, fontWeight: "900" },
  dangerSmallButton: {
    minHeight: 48,
    paddingHorizontal: 14,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: palette.red,
    backgroundColor: palette.redSoft,
    alignItems: "center",
    justifyContent: "center"
  },
  dangerSmallButtonText: { color: palette.red, fontWeight: "800" },
  totalText: { color: palette.green, fontSize: 19, fontWeight: "900" },
  filterChips: { gap: 8, paddingTop: 2, paddingBottom: 4, paddingRight: 8 },
  filterChip: {
    minHeight: 42,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: palette.line,
    paddingHorizontal: 16,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: palette.paper
  },
  filterChipActive: { backgroundColor: palette.ink, borderColor: palette.ink },
  filterChipText: { color: palette.ink, fontWeight: "900", fontSize: 13 },
  filterChipTextActive: { color: palette.inverseText },
  virtualMenuList: { padding: 14, gap: 14, paddingBottom: 118 },
  menuSection: { gap: 10 },
  menuSectionHeader: { paddingTop: 12, paddingBottom: 8, borderBottomWidth: 2, borderBottomColor: palette.line, backgroundColor: palette.paper },
  menuList: { gap: 10 },
  menuItem: {
    minHeight: 76,
    padding: 10,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: palette.lineSoft,
    backgroundColor: palette.white,
    gap: 10,
    shadowColor: palette.shadow,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 6,
    shadowOpacity: 1,
    elevation: 2
  },
  menuItemInline: { flexDirection: "row", justifyContent: "space-between", alignItems: "center" },
  menuItemVariantRow: { gap: 8 },
  menuItemStacked: { alignItems: "stretch" },
  menuIdentity: { flex: 1, minWidth: 0, flexDirection: "row", alignItems: "center", gap: 9 },
  menuCategoryIcon: {
    width: 38,
    height: 38,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center"
  },
  menuCategoryIconText: { fontSize: 16, fontWeight: "900" },
  menuText: { flex: 1, minWidth: 0 },
  menuName: { fontSize: 16, fontWeight: "900", color: palette.ink, lineHeight: 20, marginBottom: 1 },
  menuPriceBlock: { minWidth: 96, alignItems: "stretch", gap: 4, flexShrink: 0 },
  singleVariantBlock: { alignItems: "stretch" },
  variantStripBlock: { width: "46%", minWidth: 132, maxWidth: 240, flexShrink: 0 },
  variantStack: { width: "100%", maxWidth: "100%", minWidth: 0, flexShrink: 1, borderTopWidth: 1, borderTopColor: palette.lineSoft, paddingTop: 10 },
  variantWrap: { flexDirection: "row", gap: 7, alignItems: "center", paddingRight: 4 },
  variantChip: {
    minHeight: 42,
    minWidth: 108,
    flexGrow: 0,
    borderWidth: 1,
    borderColor: palette.line,
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 8,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: palette.wash
  },
  variantPrice: { color: palette.ink, fontWeight: "900", fontSize: 13 },
  price: { color: palette.greenBold, fontWeight: "900", fontSize: 14 },
  addButton: {
    minHeight: 42,
    minWidth: 92,
    borderRadius: 8,
    backgroundColor: palette.ink,
    alignItems: "center" as const,
    justifyContent: "center" as const,
    paddingHorizontal: 10
  },
  addButtonText: { color: palette.inverseText, fontSize: 13, fontWeight: "900" },
  addIndicator: { color: palette.greenBold, fontSize: 18, fontWeight: "900" },
  addText: { color: palette.ink, fontSize: 14, fontWeight: "900" },
  formStack: { gap: 9 },
  subhead: { color: palette.ink, fontWeight: "900", fontSize: 14, textTransform: "uppercase", letterSpacing: 0.2, marginBottom: 4 },
  ticketList: { gap: 8 },
  ticketLine: {
    minHeight: 74,
    padding: 10,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: palette.lineSoft,
    backgroundColor: palette.white,
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 10
  },
  ticketText: { flex: 1, minWidth: 0 },
  ticketName: { color: palette.ink, fontWeight: "900", fontSize: 15, lineHeight: 19 },
  qtyControls: { flexDirection: "row", alignItems: "center", gap: 8 },
  qtyButton: {
    width: 48,
    height: 48,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: palette.line,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: palette.paper
  },
  qtyText: { color: palette.ink, fontSize: 20, fontWeight: "900" },
  qtyValue: { color: palette.ink, fontSize: 16, fontWeight: "900", minWidth: 20, textAlign: "center" },
  sentList: { borderTopWidth: 1, borderColor: palette.lineSoft },
  sentLine: {
    minHeight: 42,
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderColor: palette.lineSoft,
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 8
  },
  sentName: { color: palette.ink, fontWeight: "800", flex: 1, lineHeight: 18 },
  totalStrip: {
    borderRadius: 8,
    backgroundColor: palette.greenSoft,
    borderWidth: 2,
    borderColor: palette.green,
    padding: 14,
    flexDirection: "row",
    justifyContent: "space-between",
    flexWrap: "wrap",
    gap: 8
  },
  totalLabel: { color: palette.green, fontWeight: "900" },
  billingPanel: {
    borderColor: palette.greenBold,
    backgroundColor: palette.greenSoft,
    gap: 12
  },
  billingStack: { gap: 12 },
  summaryGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8
  },
  summaryBox: {
    minWidth: 140,
    flex: 1,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: palette.lineSoft,
    backgroundColor: palette.white,
    padding: 10,
    gap: 3
  },
  summaryValue: { color: palette.ink, fontWeight: "900", fontSize: 17 },
  billTotals: {
    borderRadius: 8,
    borderWidth: 1,
    borderColor: palette.line,
    backgroundColor: palette.wash,
    padding: 10,
    gap: 4
  },
  historyScreenPanel: { gap: 14 },
  historyBox: {
    borderRadius: 8,
    borderWidth: 1,
    borderColor: palette.line,
    backgroundColor: palette.white,
    overflow: "hidden"
  },
  historyDayChips: {
    gap: 8,
    paddingVertical: 2
  },
  historyRow: {
    minHeight: 96,
    borderBottomWidth: 1,
    borderColor: palette.lineSoft,
    padding: 12,
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 10
  },
  historyRowHeader: { flexDirection: "row", alignItems: "flex-start", justifyContent: "space-between", gap: 10 },
  historyBillTitle: { color: palette.ink, fontSize: 16, fontWeight: "900", lineHeight: 21 },
  historyAmount: { color: palette.greenBold, fontSize: 16, fontWeight: "900", lineHeight: 21 },
  historyMeta: { color: palette.ink, fontSize: 12, fontWeight: "800", lineHeight: 17 },
  historyModifiedTag: {
    alignSelf: "flex-start",
    borderRadius: 999,
    backgroundColor: palette.blueBillSoft,
    borderWidth: 1,
    borderColor: "#bfdbfe",
    color: palette.blueBill,
    fontSize: 11,
    fontWeight: "900",
    paddingHorizontal: 8,
    paddingVertical: 2
  },
  historyActionStack: { gap: 8, alignItems: "stretch" },
  historyItemLines: { gap: 2, paddingVertical: 2 },
  historyPrintButton: {
    minHeight: 42,
    paddingHorizontal: 12
  },
  itemNoteInput: {
    marginTop: 8,
    minHeight: 40,
    fontSize: 13,
    flexBasis: "100%"
  },
  itemNoteButton: {
    alignSelf: "flex-start",
    marginTop: 8,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: palette.line,
    backgroundColor: palette.wash,
    paddingHorizontal: 10,
    paddingVertical: 6
  },
  itemNoteButtonText: {
    color: palette.muted,
    fontSize: 12,
    fontWeight: "900"
  },
  historyEditStack: { gap: 10, paddingBottom: 6 },
  historyEditLine: {
    minHeight: 52,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: palette.line,
    backgroundColor: palette.white,
    padding: 9,
    flexDirection: "row",
    alignItems: "center",
    gap: 8
  },
  historyVariantActions: { gap: 8, alignItems: "center" },
  segmentedRow: {
    flexDirection: "row",
    borderRadius: 10,
    borderWidth: 1,
    borderColor: palette.line,
    overflow: "hidden"
  },
  segmentButton: { flex: 1, minHeight: 42, alignItems: "center", justifyContent: "center", backgroundColor: palette.paper },
  segmentButtonActive: { backgroundColor: palette.ink },
  segmentText: { color: palette.ink, fontWeight: "800" },
  segmentTextActive: { color: palette.inverseText },
  paymentGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8
  },
  moneyInputWrap: { minWidth: 126, flex: 1, gap: 5 },
  quickPayGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8
  },
  quickPayButton: {
    minHeight: 50,
    minWidth: 112,
    flexGrow: 1,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: palette.green,
    backgroundColor: palette.greenSoft,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 10
  },
  quickPayText: { color: palette.greenBold, fontWeight: "900", fontSize: 14 },
  popupBackdrop: {
    flex: 1,
    backgroundColor: "rgba(21,19,15,0.5)",
    padding: 18,
    justifyContent: "center"
  },
  popupCard: {
    maxHeight: "86%",
    borderRadius: 10,
    borderWidth: 1,
    borderColor: palette.line,
    backgroundColor: palette.paper,
    padding: 14,
    gap: 12
  },
  popupScroll: { maxHeight: 460 },
  dangerButton: {
    minHeight: 44,
    borderRadius: 8,
    backgroundColor: palette.red,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 14,
    flexGrow: 1
  },
  dangerButtonText: { color: palette.inverseText, fontWeight: "800" },
  dangerText: { color: palette.red, fontWeight: "900" },
  sendButton: { flex: 1, minHeight: 48 },
  buttonDisabled: { opacity: 0.45 },
  draftBar: {
    position: "absolute",
    left: 16,
    right: 16,
    bottom: Platform.OS === "android" ? 14 : 24,
    minHeight: 74,
    borderRadius: 8,
    backgroundColor: palette.ink,
    paddingHorizontal: 16,
    paddingVertical: 12,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    shadowColor: palette.shadowStrong,
    shadowOffset: { width: 0, height: -4 },
    shadowRadius: 16,
    shadowOpacity: 1,
    elevation: 8
  },
  draftBarBadge: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: palette.green,
    alignItems: "center" as const,
    justifyContent: "center" as const
  },
  draftBarBadgeText: { color: palette.inverseText, fontSize: 13, fontWeight: "900" },
  draftBarMain: { flexDirection: "row", alignItems: "center", gap: 10, flex: 1 },
  draftBarText: { flex: 1 },
  draftBarTitle: { color: palette.inverseText, fontWeight: "900", fontSize: 17 },
  draftBarMeta: { color: palette.inverseMuted, fontSize: 12, fontWeight: "700", marginTop: 2 },
  draftBarButton: {
    minHeight: 50,
    borderRadius: 8,
    backgroundColor: palette.white,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 22
  },
  draftBarButtonText: { color: palette.ink, fontWeight: "900", fontSize: 15 },
  empty: {
    minHeight: 120,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: palette.line,
    backgroundColor: palette.white,
    alignItems: "center",
    justifyContent: "center",
    padding: 18,
    gap: 6
  },
  emptyCompact: { minHeight: 78, alignItems: "flex-start" },
  emptyTitle: { color: palette.ink, fontWeight: "900", fontSize: 15 },
  scannerShell: { flex: 1, backgroundColor: palette.scanner, paddingTop: androidStatusBarTopInset },
  scannerHeader: {
    padding: 16,
    backgroundColor: palette.paper,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12
  },
  camera: { flex: 1 },
  collapsibleWrap: {
    borderRadius: 8,
    borderWidth: 1,
    borderColor: palette.line,
    backgroundColor: palette.paper,
    overflow: "hidden" as const
  },
  collapsibleHeader: {
    minHeight: 52,
    flexDirection: "row" as const,
    alignItems: "center" as const,
    justifyContent: "space-between" as const,
    paddingHorizontal: 14,
    paddingVertical: 8,
    backgroundColor: palette.paper,
    gap: 10
  },
  collapsibleHeaderExpanded: {
    borderBottomWidth: 1,
    borderBottomColor: palette.line
  },
  collapsibleTitle: { color: palette.ink, fontSize: 16, fontWeight: "800" },
  collapsibleChevron: { color: palette.muted, fontSize: 16, fontWeight: "800" },
  collapsibleBody: { padding: 14, gap: 10 },
  kotStartButton: {
    backgroundColor: palette.amberSoft,
    borderWidth: 1,
    borderColor: palette.amber
  },
  kotStartButtonText: { color: palette.amberBold, fontWeight: "900" }
});
