import { androidStatusBarTopInset, palette } from "./app-style-tokens";

export const appShellStyles = {
  safe: { flex: 1, backgroundColor: palette.wash, paddingTop: androidStatusBarTopInset },
  keyboardShell: { flex: 1 },
  loadingShell: { flex: 1, alignItems: "center", justifyContent: "center", gap: 12 },
  loadingText: { color: palette.ink, fontWeight: "800" },
  screen: { flex: 1 },
  screenContent: { paddingHorizontal: 16, paddingTop: 12, paddingBottom: 118, gap: 12 },
  virtualMenuContent: { flex: 1 },
  onboardingContent: { paddingHorizontal: 16, paddingTop: 12, paddingBottom: 34, gap: 12 },
  header: {
    paddingHorizontal: 16,
    paddingTop: 14,
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: palette.line,
    backgroundColor: palette.paper,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
    zIndex: 10,
    elevation: 0
  },
  headerText: { flex: 1, minWidth: 0 },
  headerActions: { alignItems: "flex-end", gap: 6 },
  flexText: { flex: 1, minWidth: 0 },
  kicker: { color: palette.greenBold, fontWeight: "800", fontSize: 13, textTransform: "uppercase", letterSpacing: 0.4 },
  title: { fontSize: 24, fontWeight: "900", color: palette.ink, lineHeight: 30 },
  heroTitle: { color: palette.ink, fontSize: 28, fontWeight: "900", lineHeight: 34 },
  heroCopy: { color: palette.muted, fontSize: 14, lineHeight: 21 },
  muted: { color: palette.muted, fontSize: 12, fontWeight: "700", lineHeight: 18 },
  smallMuted: { color: palette.muted, fontSize: 12, fontWeight: "700", lineHeight: 18, paddingVertical: 4 },
  heroPanel: {
    borderRadius: 8,
    backgroundColor: palette.paper,
    borderWidth: 1,
    borderColor: palette.line,
    padding: 18,
    gap: 7,
    elevation: 0
  },
  stepCard: {
    padding: 18,
    gap: 12,
    backgroundColor: palette.paper,
    borderWidth: 1,
    borderColor: palette.line,
    borderRadius: 8,
    elevation: 0
  },
  stepHeader: { flexDirection: "row", alignItems: "center", gap: 10 },
  stepCircle: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: palette.greenBold,
    alignItems: "center",
    justifyContent: "center"
  },
  stepCircleText: { color: palette.inverseText, fontWeight: "900", fontSize: 16 },
  banner: {
    borderWidth: 1,
    borderColor: palette.line,
    backgroundColor: palette.paper,
    borderRadius: 8,
    padding: 12,
    gap: 3
  },
  bannerWarning: { borderColor: palette.amberLine, backgroundColor: palette.amberSoft },
  bannerText: { color: palette.ink, fontWeight: "800", lineHeight: 20 },
  bannerMeta: { color: palette.green, fontSize: 12, fontWeight: "800" },
  dot: { width: 12, height: 12, borderRadius: 6 },
  online: { backgroundColor: palette.green },
  offline: { backgroundColor: palette.red },
  checking: { backgroundColor: palette.amber },
  statusPill: {
    minHeight: 34,
    borderRadius: 999,
    borderWidth: 1,
    paddingHorizontal: 10,
    paddingVertical: 4,
    flexDirection: "row",
    alignItems: "center",
    gap: 6
  },
  status_online: { borderColor: palette.greenLine, backgroundColor: palette.greenSoft },
  status_offline: { borderColor: palette.redLine, backgroundColor: palette.redSoft },
  status_checking: { borderColor: palette.amberLine, backgroundColor: palette.amberSoft },
  statusText: { color: palette.ink, fontWeight: "800", fontSize: 13 },
  iconButton: {
    minHeight: 40,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: palette.line,
    paddingHorizontal: 14,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: palette.paper
  },
  iconButtonText: { color: palette.ink, fontWeight: "800", fontSize: 13 },
  cardHeader: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 10 },
  sectionTitle: { fontSize: 18, fontWeight: "900", color: palette.ink },
  serviceStats: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  serviceStat: {
    minWidth: 86,
    flexGrow: 1,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: palette.line,
    backgroundColor: palette.white,
    padding: 10,
    gap: 4
  },
  serviceStatWide: {
    minWidth: 142,
    flexGrow: 2,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: palette.greenLine,
    backgroundColor: palette.greenSoft,
    padding: 10,
    gap: 4
  },
  serviceStatValue: { color: palette.ink, fontSize: 18, fontWeight: "900" },
  inputGroup: { gap: 6 },
  inputLabel: { color: palette.muted, fontSize: 13, fontWeight: "700", textTransform: "uppercase", letterSpacing: 0.2 },
  input: {
    minHeight: 44,
    borderWidth: 1,
    borderColor: palette.line,
    borderRadius: 8,
    paddingHorizontal: 12,
    color: palette.ink,
    backgroundColor: palette.white,
    fontWeight: "600"
  },
  multilineInput: {
    minHeight: 76,
    paddingTop: 11,
    paddingBottom: 11
  },
  buttonStack: { gap: 8 },
  primaryButton: {
    minHeight: 44,
    borderRadius: 8,
    backgroundColor: palette.ink,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 16
  },
  primaryButtonText: { color: palette.inverseText, fontWeight: "800" },
  secondaryButton: {
    minHeight: 44,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: palette.line,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 14,
    backgroundColor: palette.paper
  },
  secondaryButtonText: { color: palette.ink, fontWeight: "800" },
  approvalActionActive: { backgroundColor: palette.greenSoft, borderColor: palette.green },
  approvalDangerActive: { backgroundColor: palette.red },
  scanButton: {
    minHeight: 56,
    borderRadius: 8,
    backgroundColor: palette.green,
    alignItems: "center",
    justifyContent: "center",
    gap: 3
  },
  scanButtonText: { color: palette.inverseText, fontSize: 17, fontWeight: "800" },
  scanButtonMeta: { color: palette.greenLine, fontSize: 12, fontWeight: "700" },
  modeTabs: {
    flexDirection: "row",
    padding: 5,
    borderRadius: 8,
    backgroundColor: palette.wash,
    borderWidth: 1,
    borderColor: palette.line
  },
  modeTab: { flex: 1, minHeight: 42, alignItems: "center", justifyContent: "center", borderRadius: 6, position: "relative" as const },
  modeTabActive: { backgroundColor: palette.ink },
  modeTabText: { color: palette.ink, fontWeight: "800", fontSize: 13 },
  modeTabTextActive: { color: palette.inverseText },
  modeBadge: {
    position: "absolute" as const,
    top: -2,
    right: -2,
    minWidth: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: palette.green,
    alignItems: "center" as const,
    justifyContent: "center" as const,
    paddingHorizontal: 4
  },
  modeBadgeText: { color: palette.inverseText, fontSize: 11, fontWeight: "900" },
  workArea: { gap: 12 },
  workAreaMenuOnly: { flex: 1 },
  workAreaWide: { flexDirection: "row", alignItems: "flex-start" },
  panel: {
    borderWidth: 1,
    borderColor: palette.line,
    borderRadius: 8,
    backgroundColor: palette.paper,
    padding: 14,
    gap: 12
  },
  menuPanel: { flex: 1 },
  virtualMenuPanel: { padding: 0, overflow: "hidden" },
} as const;
