import { palette } from "./app-style-tokens";

export const menuTicketStyles = {
  totalText: { color: palette.green, fontSize: 19, fontWeight: "900" },
  filterChips: { gap: 8, paddingTop: 2, paddingBottom: 4, paddingRight: 8 },
  filterChip: {
    minHeight: 42,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: palette.line,
    paddingHorizontal: 16,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: palette.paper
  },
  filterChipActive: { backgroundColor: palette.ink, borderColor: palette.ink },
  filterChipText: { color: palette.ink, fontWeight: "900", fontSize: 13 },
  filterChipTextActive: { color: palette.inverseText },
  virtualMenuList: { padding: 14, gap: 14, paddingBottom: 118 },
  menuSection: { gap: 10 },
  menuSectionHeader: { paddingTop: 12, paddingBottom: 8, borderBottomWidth: 2, borderBottomColor: palette.line, backgroundColor: palette.paper },
  menuList: { gap: 10 },
  menuItem: {
    minHeight: 76,
    padding: 10,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: palette.lineSoft,
    backgroundColor: palette.white,
    gap: 10,
    shadowColor: palette.shadow,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 6,
    shadowOpacity: 1,
    elevation: 2
  },
  menuItemInline: { flexDirection: "row", justifyContent: "space-between", alignItems: "center" },
  menuItemVariantRow: { gap: 8 },
  menuItemStacked: { alignItems: "stretch" },
  menuIdentity: { flex: 1, minWidth: 0, flexDirection: "row", alignItems: "center", gap: 9 },
  menuCategoryIcon: {
    width: 38,
    height: 38,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center"
  },
  menuCategoryIconText: { fontSize: 16, fontWeight: "900" },
  menuText: { flex: 1, minWidth: 0 },
  menuName: { fontSize: 16, fontWeight: "900", color: palette.ink, lineHeight: 20, marginBottom: 1 },
  menuPriceBlock: { minWidth: 96, alignItems: "stretch", gap: 4, flexShrink: 0 },
  singleVariantBlock: { alignItems: "stretch" },
  variantStripBlock: { width: "46%", minWidth: 132, maxWidth: 240, flexShrink: 0 },
  variantStack: { width: "100%", maxWidth: "100%", minWidth: 0, flexShrink: 1, borderTopWidth: 1, borderTopColor: palette.lineSoft, paddingTop: 10 },
  variantWrap: { flexDirection: "row", gap: 7, alignItems: "center", paddingRight: 4 },
  variantChip: {
    minHeight: 42,
    minWidth: 108,
    flexGrow: 0,
    borderWidth: 1,
    borderColor: palette.line,
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 8,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: palette.wash
  },
  variantPrice: { color: palette.ink, fontWeight: "900", fontSize: 13 },
  price: { color: palette.greenBold, fontWeight: "900", fontSize: 14 },
  addButton: {
    minHeight: 42,
    minWidth: 92,
    borderRadius: 8,
    backgroundColor: palette.ink,
    alignItems: "center" as const,
    justifyContent: "center" as const,
    paddingHorizontal: 10
  },
  addButtonText: { color: palette.inverseText, fontSize: 13, fontWeight: "900" },
  addIndicator: { color: palette.greenBold, fontSize: 18, fontWeight: "900" },
  addText: { color: palette.ink, fontSize: 14, fontWeight: "900" },
  formStack: { gap: 9 },
  subhead: { color: palette.ink, fontWeight: "900", fontSize: 14, textTransform: "uppercase", letterSpacing: 0.2, marginBottom: 4 },
  ticketList: { gap: 8 },
  ticketLine: {
    minHeight: 74,
    padding: 10,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: palette.lineSoft,
    backgroundColor: palette.white,
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 10
  },
  ticketText: { flex: 1, minWidth: 160, flexShrink: 1 },
  ticketName: { color: palette.ink, fontWeight: "900", fontSize: 15, lineHeight: 20 },
  qtyControls: { flexDirection: "row", alignItems: "center", gap: 8, flexShrink: 0 },
  qtyButton: {
    width: 48,
    height: 48,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: palette.line,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: palette.paper
  },
  qtyText: { color: palette.ink, fontSize: 20, fontWeight: "900" },
  qtyValue: { color: palette.ink, fontSize: 16, fontWeight: "900", minWidth: 20, textAlign: "center" },
  sentList: { borderTopWidth: 1, borderColor: palette.lineSoft },
  sentLine: {
    minHeight: 42,
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderColor: palette.lineSoft,
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 8
  },
  sentName: { color: palette.ink, fontWeight: "800", flex: 1, minWidth: 150, flexShrink: 1, lineHeight: 18 },
  totalStrip: {
    borderRadius: 8,
    backgroundColor: palette.greenSoft,
    borderWidth: 2,
    borderColor: palette.green,
    padding: 14,
    flexDirection: "row",
    justifyContent: "space-between",
    flexWrap: "wrap",
    gap: 8
  },
  totalLabel: { color: palette.green, fontWeight: "900" },
} as const;
