import { palette } from "./app-style-tokens";

export const serviceWorkflowStyles = {
  floorTableStack: { gap: 12 },
  floorTableGroup: { gap: 8 },
  floorTableHeader: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 8 },
  tableGrid: { flexDirection: "row", flexWrap: "wrap", justifyContent: "space-between", rowGap: 12 },
  tableTile: {
    width: "48%",
    minHeight: 92,
    padding: 12,
    borderWidth: 0,
    borderLeftWidth: 5,
    borderColor: palette.green,
    borderRadius: 8,
    backgroundColor: palette.surfaceElevated,
    justifyContent: "space-between",
    shadowColor: palette.shadow,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 6,
    shadowOpacity: 1,
    elevation: 3
  },
  busyTable: { borderColor: palette.amberBold, backgroundColor: palette.amberSoft },
  billedTable: { borderColor: palette.blueBill, backgroundColor: palette.blueBillSoft },
  selectedTable: { borderColor: palette.greenBold, backgroundColor: palette.greenSoft, shadowRadius: 10, elevation: 5 },
  tableName: { fontSize: 20, fontWeight: "900", color: palette.ink },
  tableStatus: { color: palette.green, fontWeight: "900", fontSize: 12 },
  tableStatusBusy: { color: palette.amberBold },
  tableStatusBilled: { color: palette.blueBill },
  kitchenPanel: { gap: 14 },
  kotList: { gap: 10 },
  kotCard: {
    borderWidth: 0,
    borderLeftWidth: 4,
    borderColor: palette.amber,
    borderRadius: 8,
    backgroundColor: palette.amberSoft,
    padding: 16,
    gap: 12,
    shadowColor: palette.shadow,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 8,
    shadowOpacity: 1,
    elevation: 3
  },
  kotCardPreparing: { borderColor: palette.green, backgroundColor: palette.greenSoft },
  kotCardReady: { borderColor: palette.greenBold, backgroundColor: palette.greenSoft },
  kotCardServed: { borderColor: palette.line, backgroundColor: palette.wash, opacity: 0.7 },
  kotHeader: { flexDirection: "row", alignItems: "flex-start", justifyContent: "space-between", gap: 10 },
  kotTable: { color: palette.ink, fontSize: 26, fontWeight: "900", lineHeight: 32 },
  kotStatusPill: {
    minHeight: 34,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: palette.line,
    backgroundColor: palette.paper,
    paddingHorizontal: 12,
    alignItems: "center",
    justifyContent: "center"
  },
  kotStatusReady: { borderColor: palette.greenBold, backgroundColor: palette.greenSoft },
  kotStatusText: { color: palette.muted, fontSize: 13, fontWeight: "900", textTransform: "uppercase" },
  kotStatusTextReady: { color: palette.greenBold },
  kotItems: { gap: 8 },
  kotItemRow: {
    minHeight: 48,
    borderRadius: 8,
    backgroundColor: palette.white,
    borderWidth: 1,
    borderColor: palette.lineSubtle,
    paddingHorizontal: 12,
    flexDirection: "row",
    alignItems: "center",
    gap: 10
  },
  kotQty: { minWidth: 36, color: palette.greenBold, fontSize: 20, fontWeight: "900" },
  kotItemName: { flex: 1, color: palette.ink, fontSize: 18, fontWeight: "800", lineHeight: 22 },
  kotActions: { flexDirection: "row", gap: 8 },
  kotActionButton: { flex: 1, minHeight: 54 },
  shiftGrid: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  shiftActionCard: {
    borderRadius: 8,
    borderWidth: 1,
    borderColor: palette.lineSoft,
    backgroundColor: palette.white,
    padding: 10,
    gap: 10
  },
  shiftButton: {
    minHeight: 48,
    minWidth: 76,
    paddingHorizontal: 14,
    borderRadius: 8,
    backgroundColor: palette.surfaceElevated,
    borderWidth: 1,
    borderColor: palette.line,
    alignItems: "center",
    justifyContent: "center"
  },
  shiftButtonActive: { backgroundColor: palette.greenSoft, borderColor: palette.green },
  shiftButtonText: { color: palette.ink, fontWeight: "800" },
  shiftButtonMeta: { color: palette.muted, fontWeight: "700", fontSize: 11 },
  fieldBlock: { gap: 8 },
  actionSection: {
    borderRadius: 8,
    borderWidth: 1,
    borderColor: palette.line,
    backgroundColor: palette.wash,
    padding: 12,
    gap: 10
  },
  sectionHeaderRow: { flexDirection: "row", alignItems: "flex-start", justifyContent: "space-between", gap: 10 },
  actionTitle: { color: palette.ink, fontSize: 17, fontWeight: "900", lineHeight: 22 },
  actionMeta: { color: palette.muted, fontSize: 12, fontWeight: "700", lineHeight: 17 },
  actionAmount: { color: palette.green, fontSize: 16, fontWeight: "900" },
  sendButtonRow: { flexDirection: "row", gap: 8 },
  heroSendButton: { minHeight: 62 },
  itemShiftRow: {
    minHeight: 52,
    borderWidth: 1,
    borderColor: palette.lineSoft,
    backgroundColor: palette.white,
    borderRadius: 8,
    padding: 8,
    flexDirection: "row",
    alignItems: "center",
    gap: 8
  },
  shiftQtyInput: {
    width: 42,
    minHeight: 38,
    borderWidth: 1,
    borderColor: palette.line,
    borderRadius: 8,
    textAlign: "center",
    color: palette.ink,
    fontWeight: "900",
    backgroundColor: palette.paper
  },
  transferQtyStepper: { flexDirection: "row", alignItems: "center", gap: 4, flexShrink: 0 },
  transferQtyButton: {
    width: 38,
    height: 38,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: palette.line,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: palette.wash
  },
  targetPickerList: { gap: 6 },
  targetPickerRow: {
    minHeight: 52,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: palette.lineSoft,
    backgroundColor: palette.white,
    paddingHorizontal: 12,
    paddingVertical: 8,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10
  },
  cancelPanel: {
    gap: 8,
    borderColor: palette.redLine,
    backgroundColor: palette.redSoft
  },
  stateEditor: {
    borderRadius: 8,
    borderWidth: 1,
    borderColor: palette.line,
    backgroundColor: palette.white,
    padding: 10,
    gap: 10
  },
  stateSearchResults: {
    gap: 8,
    maxHeight: 360
  },
  savedStatePill: {
    minHeight: 38,
    alignSelf: "flex-start",
    borderRadius: 8,
    borderWidth: 1,
    borderColor: palette.line,
    backgroundColor: palette.paper,
    paddingHorizontal: 12,
    alignItems: "center",
    justifyContent: "center"
  },
  savedStateText: { color: palette.muted, fontSize: 12, fontWeight: "900" },
  dangerSmallButton: {
    minHeight: 48,
    paddingHorizontal: 14,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: palette.red,
    backgroundColor: palette.redSoft,
    alignItems: "center",
    justifyContent: "center"
  },
  dangerSmallButtonText: { color: palette.red, fontWeight: "800" },
} as const;
